spring:
  application:
    name: ieseuropa
  profiles:
    active:
  datasource:
#    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MySQL;IGNORECASE=TRUE;
    url: jdbc:mysql://localhost:3306/ieseuropadb
    password: 1234
    username: root
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: noreply@gmail.com
#    password: 1234
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
  flyway:
    enabled: false # si se usa H2 (o la base de datos está vacía) hay que poner el enabled a false, por que la bbdd es nueva
    locations: classpath:/config/flyway
    baselineOnMigrate: true
    baselineVersion: 0
  jackson:
    default-property-inclusion: non_null
    mapper:
      default-view-inclusion: true
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss

logging:
  level:
    org:
      springframework:
        cache: trace

server:
  port: 8080

custom:
  username: admin@ieseuropa.es
  password: 1234
  version: 1.0
  email-enabled: false
  my-secret-token: my-secret-token
  access-token-validity: 50000
  refresh-token-validity: 50000
  #    base-url: ${server.address}:${server.port}
  base-url: localhost:8080
  protocol: http